sudo: false
dist: trusty
language: php

services:
    - rabbitmq

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer self-update
    - composer install
    - curl -LO 'https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip'
    - unzip "consul_0.6.4_linux_amd64.zip"
    - ./consul --version

script:
    - ./consul agent -bind=127.0.0.1 -server -bootstrap-expect 1 -data-dir /tmp/consul &
    - sleep 5
    - ./vendor/bin/phpunit -v -c phpunit.xml
