sudo: false
language: php

php:
    - 5.4
    - 5.5


before_script:
    - composer self-update
    - composer install
    - wget 'https://dl.bintray.com/mitchellh/consul/0.4.1_linux_amd64.zip'
    - unzip "0.4.1_linux_amd64.zip"
    - ./consul --version

script:
    - ../consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
    - ./vendor/bin/phpunit -v -c phpunit.xml
