#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
	if (file_exists($file)) {
		require_once $file;
	}
}

$app = new Fliglio\Chinchilla\Application(__DIR__ . '/../../../chinchilla.yml');
print($app->run());