#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
	if (file_exists($file)) {
		require_once $file;
	}
}

$addr = getenv('CONSUL_PORT_8500_TCP_ADDR');

$options = [];
if ($addr) {
	$options['base_url'] = sprintf("http://%s:8500", $addr);
}


$app = new Fliglio\Chinchilla\Application(__DIR__ . '/../../../chinchilla.yml', $options);
print($app->run());
